In [2]:
import numpy as np

In [52]:
x = np.fromfile('data/unsorted_array_parallel.bin', dtype=np.float64, count=10000)
nproc = 4
size_per_proc = x.shape[0] // nproc
dec = 6  # decimals

for proc in range(nproc):
    print(f'rank {proc}: ', end='')
    print(f'x[{proc*size_per_proc}] = {round(x[proc*size_per_proc], dec)} | ', end='')
    print(f'x[{((proc+1)*size_per_proc)-1}] = {round(x[((proc+1)*size_per_proc)-1], dec) }')

rank 0: x[0] = 0.840188 | x[2499] = 0.744732
rank 1: x[2500] = 0.840188 | x[4999] = 0.744732
rank 2: x[5000] = 0.700976 | x[7499] = 0.963687
rank 3: x[7500] = 0.56138 | x[9999] = 0.768991


In [55]:
x = np.fromfile('../../labs/lab10/dfile', dtype=np.int32, count=16)
nproc = 4
size_per_proc = x.shape[0] // nproc

for proc in range(nproc):
    print(f'rank {proc}: ', end='')
    print(f'x[{proc*size_per_proc}] = {round(x[proc*size_per_proc], dec)} | ', end='')
    print(f'x[{(proc+1)*size_per_proc-1}] = {round(x[(proc+1)*size_per_proc-1], dec) }')

rank 0: x[0] = 0 | x[3] = 3
rank 1: x[4] = 4 | x[7] = 7
rank 2: x[8] = 8 | x[11] = 11
rank 3: x[12] = 12 | x[15] = 15


In [56]:
x = np.fromfile('../../labs/lab10/dfile2', dtype=np.int32, count=16)
nproc = 4
size_per_proc = x.shape[0] // nproc

for proc in range(nproc):
    print(f'rank {proc}: ', end='')
    print(f'x[{proc*size_per_proc}] = {round(x[proc*size_per_proc], dec)} | ', end='')
    print(f'x[{(proc+1)*size_per_proc-1}] = {round(x[(proc+1)*size_per_proc-1], dec) }')

rank 0: x[0] = 0 | x[3] = 3
rank 1: x[4] = 1604001680 | x[7] = 21957
rank 2: x[8] = 1604001912 | x[11] = 1
rank 3: x[12] = 0 | x[15] = 4


In [58]:
np.fromfile('data/unsorted_array_parallel.bin', dtype=np.float64, count=16)

array([0.84018772, 0.39438293, 0.78309922, 0.79844003, 0.91164736,
       0.19755137, 0.33522276, 0.76822959, 0.27777471, 0.55396996,
       0.47739705, 0.62887092, 0.36478447, 0.51340091, 0.95222973,
       0.91619507])

In [2]:
np.fromfile('data/unsorted_array.bin', dtype=np.float64, count=10000)[[0,1,2,3,4,9995,9996,9997,9998,9999]]

array([0.84018772, 0.39438293, 0.78309922, 0.79844003, 0.91164736,
       0.86533269, 0.8281693 , 0.31102462, 0.37320857, 0.88876552])

In [5]:
array = np.fromfile('data/sorted_chunks.bin', dtype=np.float64, count=10000)[[0,1,2,3,4,9995,9996,9997,9998,9999]]

array([4.68776562e-05, 4.05590981e-04, 1.12547958e-03, 2.11304799e-03,
       2.20921962e-03, 9.98684356e-01, 9.98849794e-01, 9.99066878e-01,
       9.99441924e-01, 9.99695731e-01])

In [59]:
np.fromfile('../../labs/lab10/dfile', dtype=np.int32, count=16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

In [67]:
np.fromfile('../../labs/lab10/dfile2', dtype=np.int32, count=16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

In [68]:
n = 10000

In [71]:
for i in range(nproc):
    print(f'i: {i} array_size: {n / 2**i}')

i: 0 array_size: 10000.0
i: 1 array_size: 5000.0
i: 2 array_size: 2500.0
i: 3 array_size: 1250.0


In [73]:
np.log2(nproc)

2.0

In [14]:
array = np.fromfile('data/sorted_array.bin', dtype=np.float64, count=10000)

In [15]:
np.all(array == sorted(array))

True

[4.687765615381191e-05,
 8.038291711378047e-05,
 0.00022321240986846965,
 0.0004055909814339089,
 0.00041060103122638586,
 0.0005224426279414644,
 0.0006163138899096818,
 0.0007676933895646098,
 0.0008242074404024554,
 0.0008567930203195629,
 0.0008788560521224775,
 0.000952164177294897,
 0.0009567127567514371,
 0.001041309908517315,
 0.001041689888127935,
 0.0011254795832212454,
 0.0012572137644780864,
 0.001257820521135731,
 0.0013257269753728653,
 0.0013973307802329449,
 0.001460788772190357,
 0.0015850798234274051,
 0.002113047988206636,
 0.0022092196169352252,
 0.0022235852676553585,
 0.0022726752805861997,
 0.0023677349101601797,
 0.002410374117274943,
 0.0026225773629837564,
 0.002758222167733229,
 0.002815565095662868,
 0.0028277938267345514,
 0.0029256637221787424,
 0.003052580171754854,
 0.0030760844252426573,
 0.003141469323607846,
 0.0031780726291137157,
 0.003231046722843799,
 0.0032314597644058337,
 0.00328197283823135,
 0.0033322232790907024,
 0.0034580794179151207,
 0.0

In [15]:
world_size = 8
for depth in range(int(np.log2(world_size))):
    source_rank_list = [i % (2**depth) for i in range(world_size)]
    print(f'depth {depth} source rank: {source_rank_list}')
    print(f'depth {depth} swap pairs: {[[i , (i)+(2**depth)] for i in range(world_size//2)]}')

depth 0 source rank: [0, 0, 0, 0, 0, 0, 0, 0]
depth 0 swap pairs: [[0, 1], [1, 2], [2, 3], [3, 4]]
depth 1 source rank: [0, 1, 0, 1, 0, 1, 0, 1]
depth 1 swap pairs: [[0, 2], [1, 3], [2, 4], [3, 5]]
depth 2 source rank: [0, 1, 2, 3, 0, 1, 2, 3]
depth 2 swap pairs: [[0, 4], [1, 5], [2, 6], [3, 7]]


In [30]:
world_size = 8
for depth in range(int(np.log2(world_size))):
    print(f'depth: {depth}')
    for rank in range(world_size):
        if rank < 2**depth:
            source = rank
            sub_world_size = world_size // (2**depth)
            for k in range(sub_world_size):
                destination = k + (source*sub_world_size)
                print(f'source {source} --> destination {destination}')

depth: 0
source 0 --> destination 0
source 0 --> destination 1
source 0 --> destination 2
source 0 --> destination 3
source 0 --> destination 4
source 0 --> destination 5
source 0 --> destination 6
source 0 --> destination 7
depth: 1
source 0 --> destination 0
source 0 --> destination 1
source 0 --> destination 2
source 0 --> destination 3
source 1 --> destination 4
source 1 --> destination 5
source 1 --> destination 6
source 1 --> destination 7
depth: 2
source 0 --> destination 0
source 0 --> destination 1
source 1 --> destination 2
source 1 --> destination 3
source 2 --> destination 4
source 2 --> destination 5
source 3 --> destination 6
source 3 --> destination 7


In [55]:
depth, rank = 0, 0
cutoff = world_size - (world_size // (depth+1))
if cutoff != 0:
    print(world_size % cutoff)
else:
    print(0)

0


In [62]:
depth, rank = 0, 1
cutoff = world_size - (world_size // (depth+1))
if cutoff != 0:
    print(world_size / cutoff)
else:
    print(0)

0


(0, 8.0)

In [61]:
depth, rank = 1, 1
cutoff = world_size - (world_size // (depth+1))
if cutoff != 0:
    print(world_size / cutoff)
else:
    print(0)

2.0


In [60]:
depth, rank = 1, 4
cutoff = world_size - (world_size // (depth+1))
if cutoff != 0:
    print(world_size / cutoff)
else:
    print(0)

2.0


In [88]:
depth, rank = 2, 2  # --> 1
depth, world_size // (world_size-rank)

(2, 1, 0.0)

In [89]:
depth, rank = 2, 3  # --> 1
depth, world_size // (world_size-rank)

(2, 1, 1.0)

In [91]:
depth, rank = 2, 4  # --> 2
depth, world_size // (world_size-rank)

(2, 2)

In [105]:
world_size = 8
for depth in range(int(np.log2(world_size))):
    for rank in range(world_size):
        if depth == 0:
            group = 0
        else:
            group = (rank % world_size) // (2**(3-depth))
        print(f'depth: {depth}; source {group} --> rank {rank}')

depth: 0; source 0 --> rank 0
depth: 0; source 0 --> rank 1
depth: 0; source 0 --> rank 2
depth: 0; source 0 --> rank 3
depth: 0; source 0 --> rank 4
depth: 0; source 0 --> rank 5
depth: 0; source 0 --> rank 6
depth: 0; source 0 --> rank 7
depth: 1; source 0 --> rank 0
depth: 1; source 0 --> rank 1
depth: 1; source 0 --> rank 2
depth: 1; source 0 --> rank 3
depth: 1; source 1 --> rank 4
depth: 1; source 1 --> rank 5
depth: 1; source 1 --> rank 6
depth: 1; source 1 --> rank 7
depth: 2; source 0 --> rank 0
depth: 2; source 0 --> rank 1
depth: 2; source 1 --> rank 2
depth: 2; source 1 --> rank 3
depth: 2; source 2 --> rank 4
depth: 2; source 2 --> rank 5
depth: 2; source 3 --> rank 6
depth: 2; source 3 --> rank 7


In [122]:
world_size = 4
for depth in range(int(np.log2(world_size))):
    print(f'depth: {depth}')
    for rank in range(world_size):
        if rank < 2**depth:
            source = rank
            sub_world_size = world_size // (2**depth)
            for k in range(sub_world_size):
                destination = k + (source*sub_world_size)
                print(f'source {source} --> destination {destination}')

depth: 0
source 0 --> destination 0
source 0 --> destination 1
source 0 --> destination 2
source 0 --> destination 3
depth: 1
source 0 --> destination 0
source 0 --> destination 1
source 1 --> destination 2
source 1 --> destination 3


In [124]:
world_size = 4
for rank in range(world_size):
    print(f'\nrank: {rank}')
    for depth in range(int(np.log2(world_size))):
#         if depth == 0:
#             group = 0
#         else:
        group = (rank % world_size) // (2**(int(np.log2(world_size))-depth))
        print(f'depth: {depth}; source {group} --> rank {rank}')


rank: 0
depth: 0; source 0 --> rank 0
depth: 1; source 0 --> rank 0

rank: 1
depth: 0; source 0 --> rank 1
depth: 1; source 0 --> rank 1

rank: 2
depth: 0; source 0 --> rank 2
depth: 1; source 1 --> rank 2

rank: 3
depth: 0; source 0 --> rank 3
depth: 1; source 1 --> rank 3


In [128]:
int(np.log2(world_size))

2

In [127]:
2**(int(np.log2(world_size))-depth)

2

In [130]:
world_size = 4
for rank in range(world_size):
    print(f'\nrank: {rank}')
    for depth in range(int(np.log2(world_size))):
        if depth == 0:
            group = 0
        else:
            group = (rank % world_size) // (2**(int(np.log2(world_size))-depth))
        print(f'depth: {depth}; source {group} --> rank {rank}')


rank: 0
depth: 0; source 0 --> rank 0
depth: 1; source 0 --> rank 0

rank: 1
depth: 0; source 0 --> rank 1
depth: 1; source 0 --> rank 1

rank: 2
depth: 0; source 0 --> rank 2
depth: 1; source 1 --> rank 2

rank: 3
depth: 0; source 0 --> rank 3
depth: 1; source 1 --> rank 3


In [139]:
rank = 
world_size = 4
depth = int(np.log2(world_size))
current_depth = 1

(rank % world_size) / 2**(depth - current_depth)

1.0

In [140]:
world_size = 4
for rank in range(world_size):
    print(f'\nrank: {rank}')
    for depth in range(int(np.log2(world_size))):
        if depth == 0:
            group = 0
        else:
            group = (rank % world_size) // (2**(depth))
        print(f'depth: {depth}; source {group} --> rank {rank}')


rank: 0
depth: 0; source 0 --> rank 0
depth: 1; source 0 --> rank 0

rank: 1
depth: 0; source 0 --> rank 1
depth: 1; source 0 --> rank 1

rank: 2
depth: 0; source 0 --> rank 2
depth: 1; source 1 --> rank 2

rank: 3
depth: 0; source 0 --> rank 3
depth: 1; source 1 --> rank 3


In [155]:
world_size = 4
for current_depth in range(int(np.log2(world_size))):
    print(world_size - int(np.floor(world_size / 2**(current_depth))))

0
2


In [164]:
world_size = 8
depth = int(np.log2(world_size))
for current_depth in range(depth):
    print(world_size / (2**(current_depth)))

8.0
4.0
2.0


In [186]:
world_size = 8
depth = int(np.log2(world_size))
rank = 4
for current_depth in range(depth):
    partition_size = world_size / (2**current_depth)
    print(f'rank: {rank} depth: {current_depth}: pivot_source: {int((rank // partition_size) * partition_size)}')

rank: 4 depth: 0: pivot_source: 0
rank: 4 depth: 1: pivot_source: 4
rank: 4 depth: 2: pivot_source: 4


In [190]:
world_size = 8
depth = int(np.log2(world_size))
for rank in range(world_size):
    print(f'rank: {rank}')
    for current_depth in range(depth):
        partition_size = world_size // (2**current_depth)
        pivot_source = int((rank // partition_size) * partition_size)
        print(f'depth: {current_depth}: partition_size: {partition_size} pivot_source: {pivot_source}')

rank: 0
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 0
depth: 2: partition_size: 2 pivot_source: 0
rank: 1
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 0
depth: 2: partition_size: 2 pivot_source: 0
rank: 2
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 0
depth: 2: partition_size: 2 pivot_source: 2
rank: 3
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 0
depth: 2: partition_size: 2 pivot_source: 2
rank: 4
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 4
depth: 2: partition_size: 2 pivot_source: 4
rank: 5
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 4
depth: 2: partition_size: 2 pivot_source: 4
rank: 6
depth: 0: partition_size: 8 pivot_source: 0
depth: 1: partition_size: 4 pivot_source: 4
depth: 2: partition_size: 2 pivot_source: 6
rank: 7
depth: 0: pa

In [202]:
print('pivots')
world_size = 8
depth = int(np.log2(world_size))
for rank in range(world_size):
#     print(f'rank: {rank}')
    for current_depth in range(depth):
        partition_size = world_size // (2**current_depth)
        pivot_source = int((rank // partition_size) * partition_size)
        
        if rank == pivot_source:
            destination = [k + rank for k in range(partition_size)]
            print(f'depth: {current_depth} | source: {rank} | destination: {destination}')
#         print(f'depth: {current_depth}: partition_size: {partition_size} pivot_source: {pivot_source}')

pivots
depth: 0 | source: 0 | destination: [0, 1, 2, 3, 4, 5, 6, 7]
depth: 1 | source: 0 | destination: [0, 1, 2, 3]
depth: 2 | source: 0 | destination: [0, 1]
depth: 2 | source: 2 | destination: [2, 3]
depth: 1 | source: 4 | destination: [4, 5, 6, 7]
depth: 2 | source: 4 | destination: [4, 5]
depth: 2 | source: 6 | destination: [6, 7]


In [203]:
print('partitions')
world_size = 8
depth = int(np.log2(world_size))
for rank in range(world_size):
    for current_depth in range(depth):
        partition_size = world_size // (2**current_depth)
        
        if rank % 2 == 0:  # even
            print(f'depth: {current_depth} | source: {rank} | destination: {rank + 1}')
        else:  # odd
            print(f'depth: {current_depth} | source: {rank} | destination: {rank - 1}')

partitions
depth: 0 | source: 0 | destination: 1
depth: 1 | source: 0 | destination: 1
depth: 2 | source: 0 | destination: 1
depth: 0 | source: 1 | destination: 0
depth: 1 | source: 1 | destination: 0
depth: 2 | source: 1 | destination: 0
depth: 0 | source: 2 | destination: 3
depth: 1 | source: 2 | destination: 3
depth: 2 | source: 2 | destination: 3
depth: 0 | source: 3 | destination: 2
depth: 1 | source: 3 | destination: 2
depth: 2 | source: 3 | destination: 2
depth: 0 | source: 4 | destination: 5
depth: 1 | source: 4 | destination: 5
depth: 2 | source: 4 | destination: 5
depth: 0 | source: 5 | destination: 4
depth: 1 | source: 5 | destination: 4
depth: 2 | source: 5 | destination: 4
depth: 0 | source: 6 | destination: 7
depth: 1 | source: 6 | destination: 7
depth: 2 | source: 6 | destination: 7
depth: 0 | source: 7 | destination: 6
depth: 1 | source: 7 | destination: 6
depth: 2 | source: 7 | destination: 6


In [218]:
# world_size = 8
# depth = int(np.log2(world_size))
# for rank in range(world_size):
#     for current_depth in range(depth):
#         prev = world_size // (2**(current_depth))
#         partition_size = world_size // (2**(current_depth+1))
#         print(f'depth: {current_depth} | source: {rank} | partition_size: {(rank + world_size - 1) % prev}')
#         # 0 --> [0,4]   |  1 --> [1,5]  | 2 --> [2, 6]  | 4 --> [4, 0]   |  6  --> [6, 2]
#         # 0 --> [0,2]   |  1 --> [1,3]  | 2 --> [2, 0]  | 4 --> [4, 6]   |  6  --> [6, 4]
#         # 0 --> [0,1]   |  1 --> [1,0]  | 2 --> [2, 3]  | 4 --> [4, 5]   |  6  --> [6, 7]

In [3]:
world_size = 4
depth = int(np.log2(world_size))
for current_depth in range(depth):
    for rank in range(world_size):
        source = rank
        partition_size = world_size // (2**(current_depth))
        x = rank // partition_size 
    
        destination = (rank + (partition_size//2)) % partition_size
        destination += (x * partition_size)
        print(f'depth: {current_depth} | [source, destination] = [{rank},{destination}]')

depth: 0 | [source, destination] = [0,2]
depth: 0 | [source, destination] = [1,3]
depth: 0 | [source, destination] = [2,0]
depth: 0 | [source, destination] = [3,1]
depth: 1 | [source, destination] = [0,1]
depth: 1 | [source, destination] = [1,0]
depth: 1 | [source, destination] = [2,3]
depth: 1 | [source, destination] = [3,2]


In [4]:
world_size = 8
depth = int(np.log2(world_size))
for current_depth in range(depth):
    for rank in range(world_size):
        source = rank
        partition_size = world_size // (2**(current_depth))
        x = rank // partition_size 
    
        destination = (rank + (partition_size//2)) % partition_size
        destination += (x * partition_size)
        print(f'depth: {current_depth} | [source, destination] = [{rank},{destination}]')

depth: 0 | [source, destination] = [0,4]
depth: 0 | [source, destination] = [1,5]
depth: 0 | [source, destination] = [2,6]
depth: 0 | [source, destination] = [3,7]
depth: 0 | [source, destination] = [4,0]
depth: 0 | [source, destination] = [5,1]
depth: 0 | [source, destination] = [6,2]
depth: 0 | [source, destination] = [7,3]
depth: 1 | [source, destination] = [0,2]
depth: 1 | [source, destination] = [1,3]
depth: 1 | [source, destination] = [2,0]
depth: 1 | [source, destination] = [3,1]
depth: 1 | [source, destination] = [4,6]
depth: 1 | [source, destination] = [5,7]
depth: 1 | [source, destination] = [6,4]
depth: 1 | [source, destination] = [7,5]
depth: 2 | [source, destination] = [0,1]
depth: 2 | [source, destination] = [1,0]
depth: 2 | [source, destination] = [2,3]
depth: 2 | [source, destination] = [3,2]
depth: 2 | [source, destination] = [4,5]
depth: 2 | [source, destination] = [5,4]
depth: 2 | [source, destination] = [6,7]
depth: 2 | [source, destination] = [7,6]


In [288]:
lower_size = 159
upper_size = 1000-159-1

In [289]:
x[lower_size+upper_size]

999

In [226]:
depth = int(np.log2(world_size))
for rank in range(world_size):
    for current_depth in range(depth):
        source = rank
        destination = rank
        destination += (world_size / (2**(current_depth + 1)))
        destination %= world_size #2**(depth - current_depth)
#         destination = int((rank + (world_size / (2**(current_depth+1)))) % (2**(depth - current_depth)))
        print(f'depth: {current_depth} | source: {rank} | destination: {destination}')

depth: 0 | source: 0 | destination: 4.0
depth: 1 | source: 0 | destination: 2.0
depth: 2 | source: 0 | destination: 1.0
depth: 0 | source: 1 | destination: 5.0
depth: 1 | source: 1 | destination: 3.0
depth: 2 | source: 1 | destination: 2.0
depth: 0 | source: 2 | destination: 6.0
depth: 1 | source: 2 | destination: 4.0
depth: 2 | source: 2 | destination: 3.0
depth: 0 | source: 3 | destination: 7.0
depth: 1 | source: 3 | destination: 5.0
depth: 2 | source: 3 | destination: 4.0
depth: 0 | source: 4 | destination: 0.0
depth: 1 | source: 4 | destination: 6.0
depth: 2 | source: 4 | destination: 5.0
depth: 0 | source: 5 | destination: 1.0
depth: 1 | source: 5 | destination: 7.0
depth: 2 | source: 5 | destination: 6.0
depth: 0 | source: 6 | destination: 2.0
depth: 1 | source: 6 | destination: 0.0
depth: 2 | source: 6 | destination: 7.0
depth: 0 | source: 7 | destination: 3.0
depth: 1 | source: 7 | destination: 1.0
depth: 2 | source: 7 | destination: 0.0


In [13]:
world_size = 8
depth = int(np.log2(world_size))
for rank in range(world_size):
    for current_depth in range(depth):
            print(f'rank: {rank} depth: {current_depth}: pivot_source: {rank % 2**(depth - current_depth)}')

rank: 0 depth: 0: pivot_source: 0
rank: 0 depth: 1: pivot_source: 0
rank: 0 depth: 2: pivot_source: 0
rank: 1 depth: 0: pivot_source: 1
rank: 1 depth: 1: pivot_source: 1
rank: 1 depth: 2: pivot_source: 1
rank: 2 depth: 0: pivot_source: 2
rank: 2 depth: 1: pivot_source: 2
rank: 2 depth: 2: pivot_source: 0
rank: 3 depth: 0: pivot_source: 3
rank: 3 depth: 1: pivot_source: 3
rank: 3 depth: 2: pivot_source: 1
rank: 4 depth: 0: pivot_source: 4
rank: 4 depth: 1: pivot_source: 0
rank: 4 depth: 2: pivot_source: 0
rank: 5 depth: 0: pivot_source: 5
rank: 5 depth: 1: pivot_source: 1
rank: 5 depth: 2: pivot_source: 1
rank: 6 depth: 0: pivot_source: 6
rank: 6 depth: 1: pivot_source: 2
rank: 6 depth: 2: pivot_source: 0
rank: 7 depth: 0: pivot_source: 7
rank: 7 depth: 1: pivot_source: 3
rank: 7 depth: 2: pivot_source: 1


In [372]:
print('array values at depth == 0')
a = np.fromfile('../tests/test_3727_rank_0_0.out', dtype=np.float64, count=3727)
b = np.fromfile('../tests/test_3767_rank_1_0.out', dtype=np.float64, count=3767)
c = np.fromfile('../tests/test_1273_rank_2_0.out', dtype=np.float64, count=1273)
d = np.fromfile('../tests/test_1233_rank_3_0.out', dtype=np.float64, count=1233)
print(f'rank 0: {sorted(a)[:5]}')
print(f'rank 1: {sorted(b)[:5]}')
print(f'rank 2: {sorted(c)[:5]}')
print(f'rank 3: {sorted(d)[:5]}')

array values at depth == 0
rank 0: [6.3723e-319, 4.687765615381191e-05, 8.038291711378047e-05, 0.00022321240986846965, 0.0004055909814339089]
rank 1: [3.07907e-319, 0.00041060103122638586, 0.0007676933895646098, 0.0008242074404024554, 0.0008567930203195629]
rank 2: [3.07116e-319, 0.744732158139689, 0.74491614091439, 0.7450082664121912, 0.7450713891280216]
rank 3: [3.0949e-319, 0.744841486096774, 0.7451648394321859, 0.7451715221373232, 0.7454151142134402]


In [373]:
print('array values at depth == 1')
a = np.fromfile('../tests/test_2321_rank_0_1.out', dtype=np.float64, count=2321)
b = np.fromfile('../tests/test_5173_rank_1_1.out', dtype=np.float64, count=5173)
c = np.fromfile('../tests/test_2269_rank_2_1.out', dtype=np.float64, count=2269)
d = np.fromfile('../tests/test_237_rank_3_1.out', dtype=np.float64, count=237)
print(f'rank 0: {sorted(a)[:5]}')
print(f'rank 1: {sorted(b)[:5]}')
print(f'rank 2: {sorted(c)[:5]}')
print(f'rank 3: {sorted(d)[:5]}')

array values at depth == 1
rank 0: [3.07907e-319, 6.3723e-319, 6.3723e-319, 4.687765615381191e-05, 8.038291711378047e-05]
rank 1: [3.07907e-319, 3.07907e-319, 5.6577e-319, 5.6577e-319, 5.6577e-319]
rank 2: [3.07116e-319, 3.07116e-319, 3.0949e-319, 3.20397e-319, 0.744841486096774]
rank 3: [0.9783472427997493, 0.9783472427997493, 0.9785105525415906, 0.9787796512147316, 0.9789716354473362]


([6.3731e-319,
  4.687765615381191e-05,
  8.038291711378047e-05,
  0.00022321240986846965,
  0.0004055909814339089],
 [3.08223e-319,
  0.00041060103122638586,
  0.0007676933895646098,
  0.0008242074404024554,
  0.0008567930203195629],
 [3.0743e-319,
  0.744732158139689,
  0.74491614091439,
  0.7450082664121912,
  0.7450713891280216],
 [3.09804e-319,
  0.744841486096774,
  0.7451648394321859,
  0.7451715221373232,
  0.7454151142134402])

In [336]:
sorted(b)

[3.08223e-319,
 0.00041060103122638586,
 0.0007676933895646098,
 0.0008242074404024554,
 0.0008567930203195629,
 0.0008788560521224775,
 0.000952164177294897,
 0.0009567127567514371,
 0.001041309908517315,
 0.001257820521135731,
 0.0013257269753728653,
 0.0015850798234274051,
 0.0022726752805861997,
 0.0023677349101601797,
 0.002758222167733229,
 0.002815565095662868,
 0.003052580171754854,
 0.0030760844252426573,
 0.003141469323607846,
 0.0031780726291137157,
 0.00328197283823135,
 0.0033322232790907024,
 0.003463807051751673,
 0.003814779689449249,
 0.0038582868892039577,
 0.003861987033794628,
 0.003989307677368311,
 0.00420193700315521,
 0.0044803041985632406,
 0.004937937019829609,
 0.005007334987170685,
 0.0051091630035588345,
 0.005323182328288994,
 0.005483341405858911,
 0.005498006011125635,
 0.005621902181590862,
 0.005910327195148136,
 0.006591371729314035,
 0.006762945562025041,
 0.007158676165695617,
 0.007640060040932177,
 0.0077160652762819385,
 0.007892503872463714,
 0.

In [337]:
sorted(c)

[3.0743e-319,
 0.744732158139689,
 0.74491614091439,
 0.7450082664121912,
 0.7450713891280216,
 0.7451544044283938,
 0.7452919179318901,
 0.7458289976910824,
 0.7460745008411233,
 0.7461117425682543,
 0.7461451588879084,
 0.746321155105867,
 0.7463963002648187,
 0.7466352389876895,
 0.7466622370978175,
 0.7467303293509084,
 0.7472305641263866,
 0.7472771242015422,
 0.747637759310956,
 0.7478028669710285,
 0.7478092963564253,
 0.7479421262386917,
 0.7485506756922932,
 0.7486055440961409,
 0.7486783660709292,
 0.7487683192588241,
 0.7489419704065388,
 0.7492300568843401,
 0.7494431602533176,
 0.7496415375497385,
 0.7496896561932236,
 0.7497189090353059,
 0.7497708824229291,
 0.7500270413002125,
 0.750296600512367,
 0.750337116769672,
 0.750360239180904,
 0.7509234611647778,
 0.7514220898744753,
 0.7518473960235005,
 0.7518783923014433,
 0.7521208882108894,
 0.7522333961689069,
 0.7524787032755458,
 0.7529352171127383,
 0.7529706697692027,
 0.7531167211724057,
 0.7533791422626838,
 0.7533

In [338]:
sorted(d)

[3.09804e-319,
 0.744841486096774,
 0.7451648394321859,
 0.7451715221373232,
 0.7454151142134402,
 0.745873053905495,
 0.7459208349445466,
 0.7460717566991559,
 0.7461833952675496,
 0.7462850691500515,
 0.7463197786111011,
 0.7463553081016779,
 0.7468875701291895,
 0.747156884869168,
 0.7472288630657032,
 0.7481314790193604,
 0.7484038196263852,
 0.7488358042895961,
 0.7492426474342321,
 0.7494223060782171,
 0.7494570113483151,
 0.7500386013416753,
 0.7502322759247535,
 0.7503494623817268,
 0.7503744893476249,
 0.7506793880605509,
 0.7507718856217209,
 0.750901597436006,
 0.7509398231054376,
 0.7510436432208137,
 0.7512950476963516,
 0.7514390925650667,
 0.7515353908536655,
 0.7515526571085456,
 0.7515541765613268,
 0.751637632377277,
 0.7517699686585786,
 0.7519118002391941,
 0.7520803542584555,
 0.7523948469908884,
 0.7525505608658076,
 0.7528614577617783,
 0.7532419975629272,
 0.7538934460626419,
 0.7542655490125835,
 0.7546792476226944,
 0.7547433724416156,
 0.7547747384546207,
 0.

In [344]:
size = 500
x = list(range(size))
p_idx = 39

lower_size = p_idx
upper_size = len(x) - p_idx

In [345]:
x[p_idx:size]

[39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,

In [367]:
n = 10001
world_size = 4
chunk_size = n // world_size
remainder = n % chunk_size

for rank in range(world_size):
    if ((remainder != 0) & (rank+1 == world_size)):
        chunk_size += remainder
    print(f'rank {rank} chunk_size: {chunk_size}')

rank 0 chunk_size: 2500
rank 1 chunk_size: 2500
rank 2 chunk_size: 2500
rank 3 chunk_size: 2501


In [6]:
x = np.fromfile('../data/parallel/unsorted_10000000.bin', dtype=np.float64, count=10000000)

In [7]:
x.shape

(10000000,)

In [9]:
x[:5], x[-5:]

(array([0.68760083, 0.34820986, 0.99905765, 0.01719001, 0.48426126]),
 array([0.02601839, 0.34449214, 0.36321559, 0.24522045, 0.20991078]))

In [10]:
x.min()

4.377216102731049e-08

In [11]:
x.max()

0.9999996460974215